CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS post_db;
CREATE DATABASE IF NOT EXISTS social_db;
CREATE DATABASE IF NOT EXISTS feed_db;
CREATE DATABASE IF NOT EXISTS interaction_db;
