import db from "../config/db.js";

/**
 * Finds a user by either their email or username.
 * @param {string} email
 * @param {string} username
 * @returns {Promise<Object|null>} User object if found, null otherwise.
 */
export const findUserByEmailOrUsername = async (email, username) => {
  const query = "SELECT * FROM credentials WHERE email = ? OR username = ?";
  const [rows] = await db.execute(query, [email, username]);
  return rows.length > 0 ? rows[0] : null;
};

/**
 * Creates a new user in the credentials table.
 * @param {string} id - UUID generated by the controller
 * @param {string} email
 * @param {string} username
 * @param {string} passwordHash
 * @returns {Promise<Object>} The result of the insert operation.
 */
export const createUser = async (id, email, username, passwordHash) => {
  const query =
    "INSERT INTO credentials (id, email, username, password_hash) VALUES (?, ?, ?, ?)";
  const [result] = await db.execute(query, [id, email, username, passwordHash]);
  return result;
};

/**
 * Saves a refresh token to the database.
 * @param {string} id - UUID for the token
 * @param {string} userId - UUID of the user
 * @param {string} token - The refresh token string
 * @param {Date} expiresAt - Expiration date
 * @returns {Promise<Object>}
 */
export const saveRefreshToken = async (id, userId, token, expiresAt) => {
  const query =
    "INSERT INTO refresh_tokens (id, user_id, token, expires_at) VALUES (?, ?, ?, ?)";
  const [result] = await db.execute(query, [id, userId, token, expiresAt]);
  return result;
};

/**
 * Finds a user by their UUID.
 * @param {string} id
 * @returns {Promise<Object|null>}
 */
export const findUserById = async (id) => {
  const query = "SELECT * FROM credentials WHERE id = ?";
  const [rows] = await db.execute(query, [id]);
  return rows.length > 0 ? rows[0] : null;
};

/**
 * Finds a refresh token in the database.
 * @param {string} token
 * @returns {Promise<Object|null>}
 */
export const findRefreshToken = async (token) => {
  const query = "SELECT * FROM refresh_tokens WHERE token = ?";
  const [rows] = await db.execute(query, [token]);
  return rows.length > 0 ? rows[0] : null;
};

/**
 * Deletes a refresh token from the database (used for logout).
 * @param {string} token
 * @returns {Promise<Object>}
 */
export const deleteRefreshToken = async (token) => {
  const query = "DELETE FROM refresh_tokens WHERE token = ?";
  const [result] = await db.execute(query, [token]);
  return result;
};
